[package]
name = "sheetkit-node"
version = "0.5.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3", features = ["napi8", "async"] }
napi-derive = "3"
sheetkit-core = { workspace = true, features = ["encryption"] }
sheetkit-xml = { workspace = true }
tokio = { version = "1", features = ["rt"] }

[build-dependencies]
napi-build = "2"
